
### DB ###
spring:
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: jh
    password:
  sql:
    init:
      mode: embedded #always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

